name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Delete Cached Build Files
        run: |
          rm -rf _site
          jekyll clean

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.13 # Adjust based on your Jekyll version
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build the site
        run: bundle exec jekyll build --future
